### ISSUE TITLE
No Text on Server

### ISSUE THREAD

**Issue by WenXin20** [Lynzl/Minecraft-TextDamageIndicators#1]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Text Damage Indicators v1.0.0`

The text for damage taken doesn't display on a server, even though there are no errors printed in the log.

**Comment by Lynzl** [comment]
Hello!
Thanks for the report again!

I'll look into it.

Is the issue only on players or monsters too?

**Comment by WenXin20** [comment]
I'm not sure about players since I'm the only one one my server at the moment. But it's not working for any mobs.

**Comment by Mali321** [comment]
I'm having the same issue on a 1.16.3 server. I've got a handful of other mods, all client side. There are no server side mods running.
MC: 1.16.3
Forge: 34.11
TDI: 2.0.0

**Comment by Lynzl** [comment]
Duplicate of #3

**Comment by WenXin20** [comment]
Will the fix be released for 1.15.2 as well?

**Comment by Lynzl** [comment]
Yes.
