### ISSUE TITLE
Mod not getting loaded

### ISSUE THREAD

**Issue by hamtof-0** [Lynzl/Minecraft-TextDamageIndicators#2]
Mod is never loaded into minecraft.
`13:44:13.810
Preparing to launch minecraft client for fabric-loader-0.10.0+build.208-1.16.3
13:44:14.261
Checking installations.
13:44:14.262
Minecraft client fabric-loader-0.10.0+build.208-1.16.3 is ready to start.
13:44:14.263
Starting!
13:44:14.648
Using default game log configuration client-1.12.xml (outputs XML)
13:44:15.154
Loading for game Minecraft 1.16.3
13:44:15.644
[FabricLoader] Loading 41 mods: fabric-screen-handler-api-v1@1.1.0+8724984195, minecraft@1.16.3, fabric-renderer-api-v1@0.3.1+f8ac1db295, fabric-networking-blockentity-v0@0.2.5+b50ffc7b95, fabric-keybindings-v0@0.2.0+3fa9f7c595, fabric-command-api-v1@1.0.8+5ce5339895, fabricloader@0.10.0+build.208, fabric-tool-attribute-api-v1@1.2.3+f8ac1db295, fabric-renderer-indigo@0.4.1+f8ac1db295, fabric-structure-api-v1@1.1.0+f8ac1db295, fabric-containers-v0@0.1.8+045df74f95, fabric-object-builder-api-v1@1.8.1+f8ac1db295, fabric-events-interaction-v0@0.4.1+f8ac1db295, fabric-crash-report-info-v1@0.1.2+b7f9825d95, fabric-item-api-v1@1.2.0+f8ac1db295, fabric-game-rule-api-v1@1.0.2+f8ac1db295, fabric-api-base@0.1.3+12a8474c95, fabric-rendering-v0@1.1.1+f8ac1db295, fabric-rendering-v1@1.3.1+f8ac1db295, fabric-key-binding-api-v1@1.0.1+730711c695, fabric-rendering-data-attachment-v1@0.1.4+f8ac1db295, fabric-resource-loader-v0@0.3.1+facf3bbf95, fabric-textures-v0@1.0.4+eae12eb895, fabric-content-registries-v0@0.1.9+059ea86695, fabric-tag-extensions-v0@1.0.3+ac8e8c5995, fabric-rendering-fluids-v1@0.1.12+f8ac1db295, fabric-biome-api-v1@2.0.0+c29459ab95, fabric-registry-sync-v0@0.5.2+3c53fe3395, fabric-commands-v0@0.2.0+52d3083695, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8995, fabric-lifecycle-events-v1@1.2.0+74cc3b2095, fabric-mining-levels-v0@0.1.2+b764ce9995, fabric-renderer-registries-v1@2.2.0+f8ac1db295, fabric-loot-tables-v1@1.0.1+432ea18895, fabric-events-lifecycle-v0@0.2.0+16acbe5b95, fabric@0.22.1+build.409-1.16, fabric-particles-v1@0.2.2+fb0d9b0e95, fabric-models-v0@0.1.1+f8ac1db295, fabric-item-groups-v0@0.2.0+438f963695, fabric-object-builders-v0@0.7.0+432ea18895, fabric-networking-v0@0.1.10+e00ecb5f95
13:44:15.685
SpongePowered MIXIN Subsystem Version=0.8.1 Source=file:/C:/Users/Hampus%20Toft/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.1+build.21/sponge-mixin-0.8.1+build.21.jar Service=Knot/Fabric Env=CLIENT`

**Comment by hamtof-0** [comment]
full log including me joining a single player game.
https://hastebin.com/cubuvacelo.sql

**Comment by Lynzl** [comment]
Hello!
Thanks for the report.

This is a Forge mod and so not loadable by Fabric, sorry!
